/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordsearchkata;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class CrossWordTest {


    CrossWord crossWord;

    @Before
    public void setUp() {
        crossWord = new CrossWord();
    }

    @Test public void shouldReturnJO() {

        assertEquals("JO: (0,10),(0,11)", crossWord.word("JO"));
    }

    @Test public void shouldReturnJOC() {

        assertEquals("JOC: (0,10),(0,11),(0,12)", crossWord.word("JOC"));
    }

    @Test public void shouldReturnJOCWE() {

        assertEquals("JOCWE: (0,10),(0,11),(0,12),(0,13),(0,14)", crossWord.word("JOCWE"));
    }

    @Test public void shouldReturnJVN() {

        assertEquals("JVN: (0,10),(0,9),(0,8)", crossWord.word("JVN"));
    }
}
